# Calamares Settings Configuration for HENU OS 3.0
# Base: Debian 13 (Trixie)

modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - umount
  - show:
      - finished

branding: henu
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
